name: Build, publish, and deploy a Dockerized Spring app to App Service

on:
  push:
    branches:
      springdemo

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      
    # Check out repo to the VM
    - uses: actions/checkout@v1
    
    # Maven build
    - name: Build and test with Maven
      env:
        SPRING_DATASOURCE_URL: 'pythondemodb.postgres.database.azure.com:5432/postgres_demo?sslmode=require'
        SPRING_DATASOURCE_PASSWORD: 'antares@pythondemodb'
        SPRING_DATASOURCE_USERNAME: ${{ secrets.db_password }}
      run: mvn clean package

    # Finally, deploy the container to App Service
    - uses: azure/webapps-deploy@v1
      with:
        app-name: 'my-awesome-app'
        package: 'target/app.jar'
