name: Build, publish, and deploy a Dockerized Spring app to App Service

on:
  push:
    branches:
      dockerized-jar

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Maven
      run: mvn clean package
   
    # Unlike code deployment, you will authenticate using a Service Principal
    #- uses: azure/actions/login@master
    #  with:
    #    creds: ${{ secrets.AZURE_SP }}
    
    # Login to Docker
    - uses: azure/container-actions/docker-login@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    # Tag the image with the git commit hash
    - run: |
        docker build . -t JasonFreeberg/dockerspringdemo:${{ github.sha }}
        docker push JasonFreeberg/dockerspringdemo:${{ github.sha }}

    # Finally, deploy the container to App Service
    - uses: azure/appservice-actions/webapp-container@master
      with:
        app-name: '<your app name>'
        images: 'contoso/dockerspringdemo:${{ github.sha }}'

    
    