name: Build, publish, and deploy a Spring app to App Service

on:
  push:
    branches:
      springdemo

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      
    # Check out repo to the VM
    - uses: actions/checkout@v1
    
    # Maven build
    - name: Build and test with Maven
      env:
        SPRING_DATASOURCE_URL: ${{ secrets.db_url }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.db_password }}
        SPRING_DATASOURCE_USERNAME: ${{ secrets.db_username }}
      run: mvn clean package

    # Finally, deploy the container to App Service
    - uses: azure/webapps-deploy@v1
      with:
        app-name: 'spring-one-demo'
        publish-profile: ${{ secrets.CREDENTIALS }}
        package: 'target/app.jar'
